[tool.poetry]
authors = ["SaitoTsutomu <tsutomu7@hotmail.co.jp>"]
classifiers = [
  "Development Status :: 1 - Planning",
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python",
  "Topic :: Software Development",
  "Topic :: Scientific/Engineering",
]
description = "`mergepdf` is a package for merge PDF files."
homepage = "https://github.com/SaitoTsutomu/mergepdf"
license = "MIT"
name = "mergepdf"
readme = "README.rst"
version = "0.0.3"

[tool.poetry.scripts]
mergepdf = "mergepdf:main"

[tool.poetry.dependencies]
PyPDF2 = "^1.26.0"
python = "^3.7"

[tool.poetry.dev-dependencies]
black = "^19.10b0"
flake8 = "^3.7.9"
isort = "^4.3.21"
mypy = "^0.770"
pytest = "^5.2"

[build-system]
build-backend = "poetry.masonry.api"
requires = ["poetry>=0.12"]
